#!/bin/sh

xrdb ~/.Xresources &
exec nitrogen --restore &
exec xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2 &
exec mpd &
exec sxhkd &
startup &
~/.dwm/bar/./bar.sh & 
